baseURL = 'http://evg.moe'
languageCode = 'en-us'
theme="evg-theme"
paginate=100

[params]
    DateForm = "2006.01.02"

[[menu.main]]
    name = "Home"
    url = "/"
    weight =1

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight =4
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight =4
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight =6
[[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight =7
[markup]
  [markup.highlight]

    style="emacs"
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files
