baseURL = 'http://proj11.com'
languageCode = 'en-us'
theme="basic"
paginate=100
[params]
	name = "Project 77"
	description = "Your web heaven"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Editors"
    url = "/ed/"
    weight = 3
[[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight =4
