baseURL = 'http://evg.moe'
languageCode = 'en-us'
theme="dot-theme"
paginate=100

[params]
    DateForm = "2006.01.02"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight =4
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight =5
[[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight =6
[markup]
  [markup.highlight]
    noClasses=true
    style="nord"
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files
