baseURL = 'http://evg.moe'
languageCode = 'en-us'
theme="evg-theme"
[pagination]
    pagerSize=10

[params]
    DateForm = "2006.01.02"
    showIcons=false

[[menu.main]]
    name = "Home"
    url = "/"
    weight =1

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight =4
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight =4
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight =6
[[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight =7
[markup]
  [markup.highlight]
    style=""
    noHl=true
    codeFences=false
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files
