baseURL = 'http://proj11.com'
languageCode = 'en-us'
theme="basic"
paginate=100
[params]
	name = "Project 77"
	description = "Your web heaven"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Editors"
    url = "/ed/"
    weight = 2
[[menu.main]]
    name = "JS & Vue"
    url = "/js/"
    weight = 3
[[menu.main]]
    name = "File managers"
    url = "/fm/"
    weight = 4
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 5
[[menu.main]]
    name = "Rss"
    url = "/index.xml"
    weight =6
[markup]
  [markup.highlight]
    noClasses=true
    style="nord"
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files
